### ISSUE TITLE
BFin Hangs with IMU Activation Code

### ISSUE THREAD

**Issue by E3t1jump** [Engineering-3/RCM-BFin#3]
When I have an RCM full of sensors and streaming multiple data sets back to MC, when I try to run the activation code for the IMU

writei2c(0x28, 0x3D, 0x0C);
exit(0);

the BFin often hangs and stays in picoC mode requiring a reboot of the BFin. Along with this, the IMU often does not activate all readings and I will have a dead Roll (or one of the others) even after a successful running of the picoC code.

I thought it might be related to the thermal sensor also streaming across the i2c buss, but I've seen the behavior with the thermal sensor physically removed from the RCMx1.

Throwing this your way to see if:

A) you can reproduce what I'm seeing
B) determine a cause and fix

**Comment by EmbeddedMan** [comment]
You are talking about the BNO055 IMU, right?

**Comment by EmbeddedMan** [comment]
In addition, if you do not have any streaming sensors running in MC, but you just have the snippit of PicoC you listed above, does the system hang?

**Comment by E3t1jump** [comment]
Yes, BNO055.

**Comment by E3t1jump** [comment]
Maybe part of the issue?

I've noticed that if I reboot the RCM (shorting the pins) and activate Run Code, the RCM hangs in PicoC mode. Activating ESC turns off the green indicator in MainController, but the RCM hangs and requires a reboot.

I believe what is happening here is, when rebooting the RCM, the loaded code is lost. Thus, any reboot of the RCM also requires any PicoC code to be reloaded before activating Run Code.

Per this observation: is there a way to keep the RCM from hanging if Run Code is activated without any PicoC code present?

**Comment by E3t1jump** [comment]
Alternate issue (not all IMU values running): Even after physically removing all sensors and motors from the RCMx1 other than the IMU, and deactivating all sensor reads from MainController other than the IMU reads (roll, pitch, heading); there we still episodes of one of the values not activating after loading/running the IMU activation code.

**Comment by E3t1jump** [comment]
Per the Hang issue: I just went to test whether or not having the IMU reads streaming before the initialize code is loaded/run made a difference in dead reads.

A) No, this did not make a difference - still random dead reads (i.e. Pitch)
B) After I loaded the code from MC to the RCM, when I activated Run Code it hung just like it did when I activated Run Code without having loaded any PicoC code. The loading code pop-up did show, and the scale showed code load progress until full. I'm wondering if sometimes the code does not actually load, so activation of the Run Code hangs the RCM per above?

**Comment by EmbeddedMan** [comment]
OK, Tim, since I'm not able to see exactly what you're doing here, I'm getting pretty confused.

It would really help me if you listed exactly the steps you take (what code you run, what setup in the sensors setup screen, etc.) to reproduce the bug you want fixed, and then I'll focus on reproducing just that sequence and that trying to fix that bug.

**Comment by E3t1jump** [comment]
New Observation

Note: I've been describing the RCM as "hung" when the heart beat LEDs stop flashing.

Booted the RCM/Activated Run Code - MC green indicator for In PicoC stays illuminated, RCM heartbeat active.

Activate ESC - MC green indicator for In PicoC goes out, RCM heartbeat hangs.

Activate Run Code - MC green indicator for In PicoC illuminates, RCM heartbeat is now flashing as expected.

So??? What is happening here?

**Comment by E3t1jump** [comment]
I seem to be seeing multiple issues; maybe why my comments above are all over the map. I don't know if these are all related or separate, so let me know if we should start different issues for each vs. all under this issue group. I'll try and isolate each in individual comments below for now.

**Comment by E3t1jump** [comment]
Issue A - PicoC code does not load/no success count received.

Only thing attached is an IMU
Fresh power on/connect to RCM with MC/paste in the code (below)/activate Load Code

writei2c(0x28, 0x3D, 0x0C);
delay(20);
exit(1);

Loading Code pop-up shows; percent complete scale completes.
Log only displays #NRB #NRB but no success count.

Just tried this with the IMU completely removed and saw the same behavior. The behavior is random, but the last try, I left the RCM powered and just closed and reopened MC and this happened.

**Comment by E3t1jump** [comment]
Issue B - RCM "hang"? (no heartbeat) if Run Code is initiated in MC, and no code is loaded

Booted the RCM/Activated Run Code - MC green indicator for In PicoC stays illuminated, RCM heartbeat active.

Activate ESC - MC green indicator for In PicoC goes out, RCM heartbeat hangs.

Activate Run Code - MC green indicator for In PicoC illuminates, RCM heartbeat is now flashing as expected.

Once in this sequence, no other controls/communication with the RCM functions whether in or out of PicoC mode.

**Comment by E3t1jump** [comment]
It seems, that what I first reported as related to loading of the IMU code would have happened no matter what code I tried to load. The RCM hang seems to be related to Run Code when no code is present (Issue B), and what threw me was that I thought I had loaded the IMU code (but seems the code never actually loaded/Issue A). I may should edit the title on this issue to RCM Hang with False Code Load/No Code Load and Run Code.

**Comment by EmbeddedMan** [comment]
OK, let's start with Issue A - it seems from your description that simply trying to load the three lines of PicoC (with IMU attached and without) fails. Are you using test60 firmware and MC_v5.3.0? Or some other configuration?

Does this problem occur with other (older) versions of MC? Does it matter what firmware version you are running?

I just tired loading the above 3 lines of PicoC code on test60, MC_v5.3.0 twenty times, and every single time I got the output I expect "Xmodem success. Count: 128".

Do you have any sensors enabled in the sensor config window?

**Comment by E3t1jump** [comment]
I'm running MC 5.3.2; test 60 firmware.

With no sensor configs active I'm not seeing the error.
With the following sensor configs active I get the error at random intervals.

Numeric 6
Heading, Analog, 28, 1B, V/16
Signed
Streaming, 250

Numeric 7
Roll, Analog, 28, 1D, V/16
Signed
Streaming, 250

Numeric 8
Pitch, Analog, 28, 1F, V/16
Signed
Streaming, 250

**Comment by EmbeddedMan** [comment]
Ah ha! Now we are getting somewhere!

**Comment by EmbeddedMan** [comment]
And the first time I tried it, I have now gotten my system to fail just as yours is. The trick is that you have to upload code at the same time as you have streaming sensors running. (I have no IMU connected at the moment). OK, perfect. Now that I understand how to get the failure to happen, it should be a straightforward process to figure out why.

**Comment by EmbeddedMan** [comment]
After some more testing, I'm very strongly suspecting that this is a purely BFIN firmware bug - nothing to do with MC. However, I have yet to confirm that. The only time the problem happens is if you upload while you are streaming a sensor. If you stream, then turn it off, then upload - no problems. And, once you've triggered the bug, shutting down and restarting MC does nothing - all uploads will fail to produce the "Xmodem success. Count 128" message from that point until you reboot the BFin.

**Comment by E3t1jump** [comment]
Good that you could reproduce the error. I was starting to think I had a corrupt LabVIEW install/other related to my new W10 laptop. It definitely took awhile to trace through all the things I had going to get to the first dominoes in the process.

**Comment by EmbeddedMan** [comment]
OK, I think I've figured out the cause of the problem. Talking over I2C takes a while (compared to RF/serial coms) and if we start an I2C transaction (at the 250ms streaming mark) and, before it's done reading all of the I2C registers, the user tries to upload new PicoC code, we send the streaming I2C sensor response packet after the PC has begun sending the XMODEM transfer of the PicoC code, which of course messes up the XMODEM transfer.

Hmmm. Solving this one might be somewhat tricky. I'll need to think about it for awhile.

**Comment by E3t1jump** [comment]
In case this is linked, and needs to be figured into the solution:

Issue C - After running the IMU initialization code, at times there is at least one reading not updating (maybe just one/all I can recall I've seen).

I've tried to reproduce this since the discovery of the Issue A challenge, but no luck. I was thinking that if the MC Sensor Config was already set to stream data from the IMU before it was actually activated, then maybe the dead read is also an element of the I2C trying to stream data at the same time code is being passed/executed. It may be that a stream/data request is conflicting with the activation request?

**Comment by EmbeddedMan** [comment]
I may now have this problem solved. I've uploaded a new text61 version of the BFin firmware that I'd like you to test. Note, we're only trying to solve issue A at the moment.

Here's how I tested:
* I set up three streaming digital sensor reads. Each repeated every 20ms. What address they read from doesn't matter.
* I then put test60 firmware on, and uploaded the example 3-line PicoC program as above. After the second upload attempt, I had reproduced the problem (xmodem transfer failure)
* I then put test61 firmware on, and repeated the test. This time I tried 25 uploads with no failures.

The only change I made from test60 to test61 was disabling all streaming activity when performing an XMODEM transfer, then turning them back on when the transfer is complete.

Can you give it a try and see if it fixes Issue A for you as well? If so, you can try Issues B and C- maybe they're fixed too? (But probably not.)

**Comment by E3t1jump** [comment]
Yes, this solved Issue A. woot woot!!

This did NOT solve Issue B.

I have yet to test Issue C.

**Comment by E3t1jump** [comment]
Issue B - We addressed the ESC activation with exiting from a code running in PicoC, and this still works (but with maybe an element of the issue with data return values posting slowly... it would be nice if ESC is activated the data stops posting).

With Issue B, the hang occurs when Run Code is activated with no code present. In this case, activating ESC does not get the RCM out of picoC mode (heartbeat/hang as described in an earlier post).

**Comment by EmbeddedMan** [comment]
OK, it sounds to me like Issus B and C are not related to A. Would you
create separate issues for them so we can close this one and track them
separately?

**Comment by E3t1jump** [comment]
We found a conflict with data streaming while trying to load code via XMODEM. This issue was resolved with a firmware change that disables streaming when performing an XMODEM transfer (see above).

Issues B and C are not related, and will be moved to separate issues.
