### ISSUE TITLE
RCM BFin Hangs with XPico Run Code when No Code is Present

### ISSUE THREAD

**Issue by E3t1jump** [Engineering-3/RCM-BFin#4]
RCM BFin "hang"? (no heartbeat) if Run Code is initiated in MC, and no code is loaded

Booted the RCM/Activated Run Code - MC green indicator for In PicoC stays illuminated, RCM heartbeat active.

Activate ESC - MC green indicator for In PicoC goes out, RCM heartbeat hangs.

Activate Run Code - MC green indicator for In PicoC illuminates, RCM heartbeat is now flashing as expected.

Once in this sequence, no other controls/communication with the RCM functions whether in or out of PicoC mode.

**Comment by E3t1jump** [comment]
Issue C - Not all IMU data sets updating, may be associated with this RCM hang when Run Code is activated with no code present. Thus far, I've only been able to control reproducing the error after the hang/reboot RCM (by shorting the reboot pins) sequence.

**Comment by EmbeddedMan** [comment]
I have reproduced this problem with test61 firmware, and I think it should be pretty easy to solve. Going to work on this one next.

**Comment by EmbeddedMan** [comment]
I've now pushed a test62 version, which appears to fix this problem. Please test and verify that it works for you.

IMPORTANT NOTE: The code I added to test62 simply looks at the first byte of the RAM buffer where we put all things that have been XMODEMed into the Bfin. If that first byte is printable ASCII, then we assume there is a good PicoC program in RAM and we attempt to run it.

What this means is that if you use the RAM buffer for something else (for example, a firmware upload) and then try to run a PicoC program without uploading it first, there may be 'stuff' (data) left over in the RAM buffer from the previous use (firmware) which starts with a printable ASCII byte. In this case, the new code will be fooled into thinking that there is a valid PicoC program to run.

This should not be a problem in normal use. Simply rebooting the Bfin will solve the problem.

**Comment by E3t1jump** [comment]
Tested this, even after a firmware upload, and all worked well. Hopefully there will be minimal occurrence of some bits of printable ASCII residing in the RAM buffer, but it is easy to reboot on these rare occasions.

**Comment by E3t1jump** [comment]
Is it easy to add a return value for this to inform the user of the condition?

Example:
 "No Code Loaded"

**Comment by EmbeddedMan** [comment]
Possibly. I'll give it a shot.

**Comment by EmbeddedMan** [comment]
test63 version posted with error message.

**Comment by E3t1jump** [comment]
Great. Thanks.
